### ISSUE TITLE
[error] run: sudo ./sample-scheduler --authentication-kubeconfig=/etc/kubernetes/scheduler.conf --authorization-kubeconfig=/etc/kubernetes/scheduler.conf --config=scheduler-config.yaml --secure-port=10260

### ISSUE THREAD

**Issue by tatsuya1333** [ozota1/k8s-scheduling-framework-small-sample#1]
run: sudo ./sample-scheduler --authentication-kubeconfig=/etc/kubernetes/scheduler.conf --authorization-kubeconfig=/etc/kubernetes/scheduler.conf --config=scheduler-config.yaml --secure-port=10260

この操作を行った際に下のようなエラーが出てしまいます。

W0425 16:24:29.500505   25721 warnings.go:67] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget

kubernetesのバージョンによって、PodDisruptionBudgetのapiVersionを
 policy/v1beta1　から policy/v1 
に変更する必要があるようなのですが、変更する方法がわかりません。
わかる方がいらっしゃったら教えていただきたいです。
よろしくお願いいたします。

**Comment by ozota1** [comment]
Goのk8sパッケージが古いので、それを新しくしてみて動くかみてもらえますか

**Comment by tatsuya1333** [comment]
GW中で返信が遅くなってしまいすみません｡
ご返信ありがとうございます｡
無知で申し訳ないのですが､パッケージを新しくするということは､
go get k8s.io/client-go@latest
このような操作をすればよいのでしょうか?
これだけではエラーが解決できず､同じエラーが出てしまいました｡
バージョンアップに伴い､その他変更する必要があるのでしょうか?
質問が多くなってしまい申し訳ないのですが､よろしくお願い致します｡

**Comment by ozota1** [comment]
いえいえ、こちらこそ説明が不十分でした。
状況承知いたしました。
私の方で確認してちゃんとした手順をご案内しようと思うので、少々お時間ください
（お時間かかるかもしれません）

**Comment by tatsuya1333** [comment]
ご丁寧にありがとうございます！時間の方はいつでも大丈夫です｡
よろしくお願いします｡

**Comment by tatsuya1333** [comment]
自分の方でも改めて改善を行ってみているのですが､バージョンの問題などで引っかかってしまいます｡

**Comment by ozota1** [comment]
遅くなりましたが、利用するモジュールをk8s 1.23にバージョンアップしました。
1.24にはフレームワークの変更があったのか対応できませんでした。

今度はk8s 1.24に対して使うと下記の警告が出ます。

W0608 02:33:16.804888    8110 warnings.go:70] storage.k8s.io/v1beta1 CSIStorageCapacity is deprecated in v1.24+, unavailable in v1.27+; use storage.k8s.io/v1 CSIStorageCapacity

k8s自体に大量のbetaバージョンが含まれるため、これらの警告をすべて消すのは厳しいかと思います。
ただ、警告が出るだけで動作自体に問題はありません。
また、このリポジトリはただのサンプルコードなので、全てのk8sのバージョンには対応できません

**Comment by tatsuya1333** [comment]
ご丁寧にありがとうございます！
ご注釈も了解しました｡
早速試してみます
